#config_version=5

# As you add coils, you will define their name, number on the board, default_pulse. 

# Visit https://docs.missionpinball.org/en/latest/mechs/coils/ for additional information. 



coils:

#Board 3208  

  c_auto_plunger:
    number: 3208-0
    default_pulse_ms: 15 

  c_trough_eject_coil:
    number: 3208-1
    default_pulse_ms: 15  

  c_flipper_left_hold:
    number: 3208-2
    default_hold_power: .125

  c_flipper_left_full:
    number: 3208-3
    default_pulse_ms: 30

  c_flipper_right_hold:
    number: 3208-4
    default_hold_power: .125
  
  c_flipper_right_full:
    number: 3208-5
    default_pulse_ms: 30

  c_right_sling:
    number: 3208-6
    default_pulse_ms: 25

  c_left_sling:
    number: 3208-7
    default_pulse_ms: 25

  c_pop_bumper_1:
    number: 0804-0
    default_pulse_ms: 35

  c_pop_bumper_2:
    number: 0804-1
    default_pulse_ms: 35

  c_pop_bumper_3:
    number: 0804-2
    default_pulse_ms: 35






#Autofire devices are defined here by switch and what coil is cycled when that switch is active. 

autofire_coils:

  slingshot_left:
    coil: c_left_sling
    switch: s_left_sling

  slingshot_right:
    coil: c_right_sling
    switch: s_right_sling

  popbumper_1:
    coil: c_pop_bumper_1
    switch: s_pop_bumper_1

  popbumper_2:
    coil: c_pop_bumper_2
    switch: s_pop_bumper_2

  popbumper_3:
    coil: c_pop_bumper_3
    switch: s_pop_bumper_3
