#config_version=5

# This config is only valid for MPF 0.56.1

hardware:
    platform: fast


fast:

  net:
    controller: neuron
    port: COM4
    io_loop:

#Here is where you willed any additional switch / driver boards. Order is counted by 1 beginning connected to the neuron and then each one added would be order: 2, order: 3. The name of the board can be anything and will be used when defining coils or switches. 

      3208:
        model: FP-I/O-3208
        order: 1

#Config for Neuron controller and expansion boards. Playfield can be changed to any name, and this will what you will use for beginning address of each led on that expansion board (serial lets, WS2812, etc). 

  exp:
    port: COM3
    boards: 
      playfield:
        model: FP-EXP-0081
        led_fade_time: 0
      neuron:
        model: FP-EXP-2000
        breakouts:
          - port: 1
            model: FP-PWR-0007

#Window is your total size for your displays, below is setup for use with one 1080p monitor. 
   
window:
  width: 1920
  height: 1080
  title: MPF All Display Window
  fullscreen: false
  resizable: true
  borderless: true
  exit_on_escape: true
  no_window: false
  show_cursor: no 


displays:

  window:
    width: 1920
    height: 1080
  display1:
    width: 1920
    height: 1080



slides:
  slide_layout:
    target: window
    background_color: white #white for test
    widgets: 
      - type: display
        source_display: display1
        width: 1920
        height: 1080
        x: right
        anchor_x: right


slide_player:
  mc_ready:
    slide_layout:
      target: window 

#Game Config

config:
  - lights.yaml
  - coils.yaml
  - switches.yaml
  - sounds.yaml
  - images.yaml
  - videos.yaml


playfields:
  #Define your playfields

  playfield:
    default_source_device: bd_plunger
    tags: default

machine:
    balls_installed: 3

game:
    balls_per_game: 3
    max_players: 4
    
modes:
  - base
  - attract

       
flippers:

    left_flipper:
        main_coil: c_flipper_left_full
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        eos_switch: s_left_flipper_eos
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, service_mode_entered, disableAutofire

    right_flipper:
        main_coil: c_flipper_right_full
        hold_coil: c_flipper_right_hold
        eos_switch: s_right_flipper_eos
        activation_switch: s_right_flipper
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, service_mode_entered, disableAutofire

ball_devices:

  bd_trough:

    ball_switches: s_trough_ball_1, s_trough_ball_2, s_trough_ball_3
    tags: trough, home, drain
    eject_coil: c_trough_eject_coil
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 2s

  bd_plunger:
    ball_switches: s_plunger
    mechanical_eject: true
    eject_timeouts: 5s

#Example Drop Target Bank setup. This can be setup how you need it

#drop_targets:
#    lowerDrop1_target:
#         switch: s_lowerDrop1
#    lowerDrop2_target:
#         switch: s_lowerDrop2


drop_target_banks:

#    TEAM_bank:
#        drop_targets: lowerDrop1_target, lowerDrop2_target
#        reset_coil: c_reset_4bank
#        reset_coil_max_wait_ms: 150
#        reset_events: 
#           machine_reset_phase_3: 100ms
#           ball_starting: 100ms
keyboard:

  s:
    switch: s_start
  1:
    switch: s_trough_ball_1
    toggle: true
  2:
    switch: s_trough_ball_2
    toggle: true
  3:
    switch: s_trough_ball_3
    toggle: true
  4:
    switch: s_trough_ball_4
    toggle: true
  5:
    switch: s_trough_ball_5
    toggle: true
  6:
    switch: s_trough_ball_6
    toggle: true

