#config_version=5

sound_system:
  tracks: #not music tracks, more like channels in audio mixer
    music:
      type: standard
      simultaneous_sounds: 1
      volume: 1.0
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.7
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 1.0
      
assets:
  sounds:
    default:
      load: on_demand
    music:
      track: music
    sfx:
      track: sfx
    voice:
      track: voice      
      
      
sounds:
  music_bg1:  
    file: worlds.wav
    volume: 1.0
    priority: 100
    about_to_finish_time: 2s
    events_when_about_to_finish: music_bg1_about_to_finish
  sfx_welcome:  
    file: Welcome.wav 
    volume: 1.0
    priority: 300
    about_to_finish_time: 2s
    events_when_about_to_finish: sfx_welcome_about_to_finish
